version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.06.0-ce
      - run:
          name: Grant maven permission
          command: chmod +x mvnw
      - run:
          name: Build spring boot jar
          command: mvn clean package -DskipTests
      - run:
          name: Build Docker image
          command: |
            echo 'export IMAGE_TAG=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)' >> $BASH_ENV
            echo 'export PROJECT_NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)' >> $BASH_ENV
            echo 'export IMAGE_NAME=$DOCKER_USER/$PROJECT_NAME' >> $BASH_ENV
            source $BASH_ENV
            docker build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile.local .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_USER" | docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
            docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
workflows:
    version: 2
    build:
        jobs:
          - build:
              context: DOCKER
              filters:
                branches:
                  only: master