version: 2
jobs:
  build-and-publish:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Initial Environment variavle
          command: |
            echo 'export IMAGE_TAG=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)' >> $BASH_ENV
            echo 'export PROJECT_NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)' >> $BASH_ENV
            echo 'export IMAGE_NAME=$DOCKER_USER/$PROJECT_NAME' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Build spring boot jar
          command: |
            chmod +x mvnw
            mvn clean package -DskipTests
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_USER" | docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
            docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2
  build:
    jobs:
      - build-and-publish:
          context: DOCKER
          filters:
            branches:
              only: master